
import "./globals.css";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import ChatWidget from "@/components/ChatWidget";
import { Analytics } from "@vercel/analytics/next"

export const metadata: Metadata = {
  title: "Shivam Somya | Product Manager",
  description:
    " Shivam Somya – Product Manager building scalable B2B products.",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-textMain min-h-screen">
        <Navbar />
        {children}
         <ChatWidget />
          <Analytics />
      </body>
    </html>
  );
}


/*
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";





const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
/*
export const metadata = {
  title: "Shivam Somya | Product Manager",
  description: "Product Manager & AI-first Development Partner",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-background text-textMain min-h-screen">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}*/



/*
export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}*/
